[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "resume-2025-novabright"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
openai = ">=1.82.1,<2"
pip = ">=25.1.1,<26"
max = ">=25.4.0.dev2025060220,<26"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.3,<4"
